name: ForumDemo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  print-stuff:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: pwd
        - name: List files
          run: ls
  build-project: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .net
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 8.0
    - name: Build project
      run: dotnet build
    - name: Upload-artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ConsoleApp
        path: ./MusicPlayer/bin/Debug/net8.0/
